In [1]:
%matplotlib inline

import os, sys

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
import collections

In [3]:
Card = collections.namedtuple('Card', ['rank', 'suit'])

class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)]+list('JQKA')
    suits = 'spades diamonds clubs hearts'.split()
    
    def __init__(self):
        self._cards = [Card(rank, suit) for suit in self.suits for rank in self.ranks]
        
    def __len__(self):
        return len(self._cards)
    
    def __getitem__(self, position):
        return self._cards[position]

In [4]:
deck = FrenchDeck()

In [7]:
deck[-1]

Card(rank='A', suit='hearts')

In [8]:
from random import choice

In [11]:
choice(deck)

Card(rank='2', suit='clubs')

In [12]:
deck[:2]

[Card(rank='2', suit='spades'), Card(rank='3', suit='spades')]

In [15]:
Card('Q', 'hearts') in deck

True

In [16]:
suit_values = dict(spades=3, hearts=2, diamonds=1, clubs=0)
def spades_high(card):
    rank_value = FrenchDeck.ranks.index(card.rank)
    return rank_value*len(suit_values)+suit_values[card.suit]

In [19]:
from math import hypot

In [21]:
class Vector:
    def __init__(self, x=0, y=0):
        self.x, self.y = x, y
    
    def __repr__(self):
        return 'Vector(%r, %r)' % (self.x, self.y)
    
    def __abs__(self):
        return hypot(self.x, self.y)
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        return Vector(self.x+other.x, self.y+other.y)

    def __mul__(self, scalar):
        return Vector(self.x*scalar, self.y*scalar)

In [26]:
np.array([0, 1.2, 2], dtype='f').astype(int)

array([0, 1, 2])

In [27]:
import io

In [28]:
data = '1, 2, 3\n4, 5, 6'

In [51]:
np.genfromtxt(io.BytesIO(open('temp/npio', 'rb').read()), delimiter=',', comments='--', names='a, b, c', usecols='a, c')

array([( 1.,  3.), ( 3.,  3.)],
      dtype=[('a', '<f8'), ('c', '<f8')])

In [33]:
fin = open('temp/npio')

In [42]:
io.BytesIO(b'1, 2, 3, 4, 5, 6, ')

In [38]:
open('temp/npio', 'rb').read()

b'1, 2, 3\n3, 2, 2'

In [52]:
a = np.arange(3)

In [53]:
b = a+1

In [58]:
np.cross(a, b)

array([-1,  2, -1])

In [63]:
(a**2).sum()**0.5

2.2360679774997898

In [66]:
a = np.random.random((3, 4))

In [67]:
a

array([[ 0.63850002,  0.51748722,  0.78209868,  0.33739848],
       [ 0.83057517,  0.04005587,  0.07949316,  0.01895829],
       [ 0.74551316,  0.07663832,  0.80454111,  0.52933282]])

In [70]:
a.dtype.names = ('c0', 'c1', 'c2', 'c3')

ValueError: there are no fields defined